### ISSUE TITLE
Spring Retrospective #8

### ISSUE THREAD

**Issue by eddie-ma-1** [dartmouth-cs98/21f-visuol#228]

**Comment by eddie-ma-1** [comment]
## Sprint #8 Retrospective:
* members in attendance:
  ![selfie proof of meeting](https://i.imgur.com/5Fsexbq.jpg)


  - [x] James
  - [x] Eddie
  - [x] Raymond
  - [x] Nina
  - [x] Austin
* what worked well
    * Deployed the app!
        * We're using Github Pages to host our front end ([link](https://https://dartmouth-cs98.github.io/)). ![Screenshot](https://i.imgur.com/UL0KAPP.png)
        * We're using Heroku to host the backend. 
    * Finished page on Healthcare information
    * Fixed another state tax bug. Alaska used to break the offer form with compensation showing as 0. We realized it was because Alaska has no state taxes and so our scraped information in our database was missing some data columns. We now account for this edge case. 
    * Team collectively made finals for Women's Masters

* what didn't
    * We had some issues with deploying the backend. It mainly had to due with dependicies. We've managed to fix some of them though and have deployed something.
    * Currently, links on our deployed github page don't work.
* self assessment on progress
    * It's been a great week! We've deployed our app and the core features are working. We've fixed a decent number of bugs here and there but will be on the lookout for others before demo day.
    * Week 9: 
        * Finish Medium Article
        * Clean up some bugs and refine some recent features.
* briefly summarize any other topics/discussions

**Comment by timofei7** [comment]
great!  maybe lets create a better domain than https://dartmouth-cs98.github.io/21f-visuol/ for the product - anybody want to register something like a .me domain?  also the problem with github pages is it doesn't work for SPA routes very well.  for instance if you reload any of the frontend routes like https://dartmouth-cs98.github.io/21f-visuol/new-offer. you get a page now found error.  would recommend netlify or render.com instead of ghpages.   even creating a new offer looks like it triggers a reload automatically (shouldn't need to do that btw) so things like https://dartmouth-cs98.github.io/21f-visuol/LoadGraphs/BrunchLabs/62252ea22f0767c7002f69cb. end up not working and someone has to revisit the page manually.

**Comment by timofei7** [comment]
also sometimes adjusting the annual bonus slider causes the numbers on the graph to disappear and not be recalculated.

**Comment by timofei7** [comment]
<img width="985" alt="Screen Shot 2022-03-06 at 5 02 21 PM" src="https://user-images.githubusercontent.com/1221134/156943970-7ab9f919-767b-4c33-a597-7e61b3768f1b.png">

assuming units are dollars but should add that for clarity.

**Comment by timofei7** [comment]
days until launch says 33?

<img width="305" alt="Screen Shot 2022-03-06 at 5 04 55 PM" src="https://user-images.githubusercontent.com/1221134/156944045-8aa2778e-ea31-4ef0-8a85-211744dfcbdb.png">
